//! Writes config.toml and .env from collected wizard answers.
//!
//! config.toml is generated as a human-readable commented TOML string —
//! not via serde serialization — so comments and structure are preserved.
//! .env is written with 0600 permissions; existing keys are never overwritten.

use std::fs;
use std::io::Write as _;
use std::path::Path;

use anyhow::Result;

use super::answers::{Answers, BotProfile};

// ── public entry points ────────────────────────────────────────────────────

pub fn write_config(answers: &Answers, path: &Path) -> Result<()> {
    fs::create_dir_all(path.parent().unwrap_or(path))?;

    let (default_agent, agents_block) = render_agents_block(&answers.profile);

    let axum_enabled = answers.enable_http;
    let tg_enabled = answers.enable_telegram;
    let bind = &answers.http_bind;
    let work_dir = answers.work_dir.display().to_string();
    let bot_name = &answers.bot_name;
    let api_base = &answers.llm_api_base_url;
    let model = &answers.llm_model;

    let toml = format!(
        r#"# Araliya Bot — generated by `araliya-bot setup`
# Edit freely. Run `araliya-bot setup` to regenerate.
# Secrets (API keys, tokens) are in .env next to this file.

[supervisor]
bot_name = "{bot_name}"
work_dir = "{work_dir}"
log_level = "info"

## ── Comms ────────────────────────────────────────────────────────────────

[comms.pty]
# PTY (interactive terminal). Activated at runtime with -i flag.
enabled = true

[comms.telegram]
# Requires TELEGRAM_BOT_TOKEN in .env
enabled = {tg_enabled}

[comms.axum_channel]
# HTTP channel — web UI + REST API
enabled = {axum_enabled}
bind = "{bind}"

## ── Agents ───────────────────────────────────────────────────────────────

[agents]
default = "{default_agent}"
debug_logging = false

[agents.routing]
# Optional: channel_id -> agent_id overrides

{agents_block}

## ── Memory ───────────────────────────────────────────────────────────────

[memory.basic_session]

## ── LLM ──────────────────────────────────────────────────────────────────

[llm]
default = "openai"

[llm.providers.openai]
api_type = "chat_completions"
api_base_url = "{api_base}"
model = "{model}"
temperature = 0.2
timeout_seconds = 600
input_per_million_usd = 0.0
output_per_million_usd = 0.0
cached_input_per_million_usd = 0.0

## ── Runtimes ─────────────────────────────────────────────────────────────

[runtimes]
enabled = false
default_timeout_secs = 30

## ── Tools ────────────────────────────────────────────────────────────────

[tools.newsmail_aggregator]
label_ids = ["INBOX"]
n_last = 10

## ── UI ───────────────────────────────────────────────────────────────────

[ui.svui]
enabled = {axum_enabled}
static_dir = "frontend/build"
"#
    );

    fs::write(path, toml)?;
    Ok(())
}

pub fn write_env(answers: &Answers, path: &Path) -> Result<()> {
    fs::create_dir_all(path.parent().unwrap_or(path))?;

    // Read existing content so we don't overwrite keys the user already has.
    let existing = if path.exists() {
        fs::read_to_string(path)?
    } else {
        String::new()
    };

    let mut new_lines: Vec<String> = Vec::new();

    maybe_add_key(
        &existing,
        &mut new_lines,
        "OPENAI_API_KEY",
        &answers.openai_api_key,
    );

    if let Some(token) = &answers.telegram_token {
        maybe_add_key(&existing, &mut new_lines, "TELEGRAM_BOT_TOKEN", token);
    }

    if new_lines.is_empty() {
        // Nothing new to write — file already has all keys.
        return Ok(());
    }

    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)?;

    // Ensure we start on a fresh line if the file already has content.
    if !existing.is_empty() && !existing.ends_with('\n') {
        writeln!(file)?;
    }

    for line in &new_lines {
        writeln!(file, "{line}")?;
    }

    // Set permissions to 0600 (owner read/write only).
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
    }

    Ok(())
}

// ── helpers ────────────────────────────────────────────────────────────────

fn maybe_add_key(existing: &str, lines: &mut Vec<String>, key: &str, value: &str) {
    if value.is_empty() {
        return;
    }
    // Skip if this key is already present (any value).
    if existing.lines().any(|l| l.starts_with(&format!("{key}="))) {
        return;
    }
    lines.push(format!("{key}={value}"));
}

fn render_agents_block(profile: &BotProfile) -> (&'static str, String) {
    match profile {
        BotProfile::BasicChat => ("basic_chat", "[agents.basic_chat]\nenabled = true\n".into()),
        BotProfile::SessionChat => (
            "chat",
            "[agents.chat]\nenabled = true\nmemory = [\"basic_session\"]\n".into(),
        ),
        BotProfile::AgenticChat => (
            "agentic-chat",
            concat!(
                "[agents.chat]\nenabled = true\nmemory = [\"basic_session\"]\n\n",
                "[agents.agentic-chat]\nenabled = true\nmemory = [\"basic_session\"]\n",
                "use_instruction_llm = false\n"
            )
            .into(),
        ),
        BotProfile::Docs => (
            "docs",
            concat!(
                "[agents.chat]\nenabled = true\nmemory = [\"basic_session\"]\n\n",
                "[agents.docs]\nenabled = true\ndocsdir = \"docs/\"\nindex = \"index.md\"\n",
                "memory = [\"basic_session\"]\n"
            )
            .into(),
        ),
        BotProfile::Newsroom => (
            "newsroom",
            concat!(
                "[agents.newsroom]\nenabled = true\nmemory = [\"basic_session\"]\n\n",
                "[agents.newsroom.gdelt_query]\nlookback_minutes = 60\nlimit = 50\n",
                "min_articles = 1\n"
            )
            .into(),
        ),
        BotProfile::Custom => ("echo", String::new()),
    }
}

// ── tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::setup::answers::*;
    use std::path::PathBuf;
    use tempfile::TempDir;

    fn dummy_answers() -> Answers {
        Answers {
            bot_name: "testbot".into(),
            work_dir: PathBuf::from("/tmp/testbot"),
            config_dir: PathBuf::from("/tmp/testbot-config"),
            llm_provider: LlmProvider::OpenAI,
            openai_api_key: "sk-test-key".into(),
            llm_model: "gpt-4o-mini".into(),
            llm_api_base_url: "https://api.openai.com/v1/chat/completions".into(),
            profile: BotProfile::BasicChat,
            enable_http: true,
            http_bind: "127.0.0.1:8080".into(),
            enable_telegram: false,
            telegram_token: None,
        }
    }

    #[test]
    fn test_write_config_creates_valid_toml() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");
        write_config(&dummy_answers(), &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        // Parse it — must be valid TOML
        let parsed: toml::Value = toml::from_str(&content).expect("invalid TOML output");

        // Spot-check key fields
        let sup = &parsed["supervisor"];
        assert_eq!(sup["bot_name"].as_str().unwrap(), "testbot");
        assert_eq!(sup["work_dir"].as_str().unwrap(), "/tmp/testbot");
        assert!(parsed.get("llm").is_some());
        assert!(parsed.get("agents").is_some());

        let axum = &parsed["comms"]["axum_channel"];
        assert_eq!(axum["enabled"].as_bool().unwrap(), true);
    }

    #[test]
    fn test_write_config_agent_profile_basic_chat() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");
        write_config(&dummy_answers(), &path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        let parsed: toml::Value = toml::from_str(&content).unwrap();
        assert_eq!(parsed["agents"]["default"].as_str().unwrap(), "basic_chat");
    }

    #[test]
    fn test_write_config_agent_profile_newsroom() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("config.toml");
        let mut answers = dummy_answers();
        answers.profile = BotProfile::Newsroom;
        write_config(&answers, &path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        let parsed: toml::Value = toml::from_str(&content).unwrap();
        assert_eq!(parsed["agents"]["default"].as_str().unwrap(), "newsroom");
    }

    #[test]
    fn test_write_env_creates_file_with_api_key() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".env");
        write_env(&dummy_answers(), &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("OPENAI_API_KEY=sk-test-key"));
    }

    #[test]
    fn test_write_env_does_not_duplicate_existing_key() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".env");
        // Pre-seed the file with the key
        fs::write(&path, "OPENAI_API_KEY=already-here\n").unwrap();

        write_env(&dummy_answers(), &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        // Must appear exactly once
        assert_eq!(content.matches("OPENAI_API_KEY=").count(), 1);
    }

    #[test]
    fn test_write_env_permissions() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".env");
        write_env(&dummy_answers(), &path).unwrap();

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt as _;
            let meta = std::fs::metadata(&path).unwrap();
            assert_eq!(meta.permissions().mode() & 0o777, 0o600);
        }
    }

    #[test]
    fn test_write_env_includes_telegram_token() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".env");
        let mut answers = dummy_answers();
        answers.enable_telegram = true;
        answers.telegram_token = Some("bot123456:ABC-secret".into());
        write_env(&answers, &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("TELEGRAM_BOT_TOKEN=bot123456:ABC-secret"));
    }
}
